"""Build-time QR code generator for Eat Well.

For every restaurant in data/restaurants.json, encodes a MapQuest search URL
(https://www.mapquest.com/search/results?query=...) as a QR matrix and writes
eat_well/qr_data.py with the packed bit data. The badge has no QR library, so
the matrices are precomputed here and drawn as plain rectangles at runtime.

Run:  python3 scripts/make_qr.py
"""

import json
import os
from urllib.parse import quote_plus

import segno

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(HERE, "eat_well", "data", "restaurants.json")
OUT = os.path.join(HERE, "eat_well", "qr_data.py")

BASE = "https://www.mapquest.com/search/results?query="


def mapquest_url(name, city_name):
    return BASE + quote_plus(name + " " + city_name)


def pack(matrix):
    size = len(matrix)
    bits = []
    for row in matrix:
        bits.extend(1 if v else 0 for v in row)
    # pad to whole bytes
    while len(bits) % 8:
        bits.append(0)
    raw = bytearray()
    for i in range(0, len(bits), 8):
        byte = 0
        for b in bits[i:i + 8]:
            byte = (byte << 1) | b
        raw.append(byte)
    return size, raw.hex()


def main():
    with open(DATA) as f:
        app = json.load(f)
    entries = []
    max_size = 0
    longest_url = 0
    for city in app["cities"]:
        for spot in city["restaurants"]:
            url = mapquest_url(spot["name"], city["name"])
            longest_url = max(longest_url, len(url))
            qr = segno.make(url, error="l")
            size, hexdata = pack(qr.matrix)
            max_size = max(max_size, size)
            key = city["id"] + "|" + spot["name"]
            entries.append((key, size, hexdata, url))
    with open(OUT, "w") as f:
        f.write('"""Precomputed QR codes (MapQuest search URLs), generated by scripts/make_qr.py.\n')
        f.write('Do not edit by hand. Key: "city_id|restaurant name" -> (matrix size, packed bits hex).\n')
        f.write('"""\n\nQR = {\n')
        for key, size, hexdata, url in entries:
            f.write("# %s\n" % url)
            f.write('"%s": (%d, "%s"),\n' % (key, size, hexdata))
        f.write("}\n")
    total_bytes = sum(len(h) // 2 for _, _, h, _ in entries)
    print("Wrote %s: %d codes, largest %dx%d, longest URL %d chars, %d bytes packed."
          % (OUT, len(entries), max_size, max_size, longest_url, total_bytes))


if __name__ == "__main__":
    main()
