"""Build-time QR code generator for Eat Well.

For every restaurant in data/restaurants.json, encodes its specific MapQuest
listing URL (from the unified linkmap) as a QR matrix and writes
eat_well/qr_data.py with the packed bit data. The badge has no QR library, so
the matrices are precomputed here and drawn as plain rectangles at runtime.

Restaurants without a specific listing URL fall back to a MapQuest search URL.

The linkmap lives in ~/workspace/ewdata/mq/ (persistent, survives VM restarts):
  seed_links.json   - 80 verified links (original mapq.st + 1 manual)
  found.json        - Firecrawl search finds
  agent_links.json  - validated Firecrawl Agent results

Run:  python3 scripts/make_qr.py
"""

import json
import os
from urllib.parse import quote_plus

import segno

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(HERE, "eat_well", "data", "restaurants.json")
OUT = os.path.join(HERE, "eat_well", "qr_data.py")
MQDIR = os.path.expanduser("~/workspace/ewdata/mq")

BASE = "https://www.mapquest.com/search/results?query="


def load_linkmap():
    """Union of all link sources. Priority: seed > agent > found."""
    linkmap = {}
    for fname in ("found.json", "agent_links.json", "seed_links.json"):
        path = os.path.join(MQDIR, fname)
        if not os.path.exists(path):
            continue
        with open(path) as f:
            linkmap.update(json.load(f))
    return linkmap


def mapquest_url(name, city_name):
    return BASE + quote_plus(name + " " + city_name)


def pack(matrix):
    size = len(matrix)
    bits = []
    for row in matrix:
        bits.extend(1 if v else 0 for v in row)
    # pad to whole bytes
    while len(bits) % 8:
        bits.append(0)
    raw = bytearray()
    for i in range(0, len(bits), 8):
        byte = 0
        for b in bits[i:i + 8]:
            byte = (byte << 1) | b
        raw.append(byte)
    return size, raw.hex()


def main():
    with open(DATA) as f:
        app = json.load(f)
    linkmap = load_linkmap()
    print(f"linkmap: {len(linkmap)} specific URLs loaded")
    entries = []
    max_size = 0
    longest_url = 0
    n_specific = n_fallback = 0
    for city in app["cities"]:
        for spot in city["restaurants"]:
            key = city["id"] + "|" + spot["name"]
            url = linkmap.get(key)
            if url:
                n_specific += 1
            else:
                url = mapquest_url(spot["name"], city["name"])
                n_fallback += 1
            longest_url = max(longest_url, len(url))
            qr = segno.make(url, error="l")
            size, hexdata = pack(qr.matrix)
            max_size = max(max_size, size)
            entries.append((key, size, hexdata, url))
    with open(OUT, "w") as f:
        f.write('"""Precomputed QR codes (specific MapQuest listing URLs; search-URL fallback\n')
        f.write('where no listing was found), generated by scripts/make_qr.py.\n')
        f.write('Do not edit by hand. Key: "city_id|restaurant name" -> (matrix size, packed bits hex).\n')
        f.write('"""\n\nQR = {\n')
        for key, size, hexdata, url in entries:
            f.write("# %s\n" % url)
            f.write('"%s": (%d, "%s"),\n' % (key, size, hexdata))
        f.write("}\n")
    total_bytes = sum(len(h) // 2 for _, _, h, _ in entries)
    print("Wrote %s: %d codes (%d specific URLs, %d search fallbacks), "
          "largest %dx%d, longest URL %d chars, %d bytes packed."
          % (OUT, len(entries), n_specific, n_fallback,
             max_size, max_size, longest_url, total_bytes))


if __name__ == "__main__":
    main()
