"""Convert Firefly pixel-art PNGs into compact RLE sprite data for Badgeware.

Badgeware has no image blit, so sprites are stored as run-length encoded
rows: each run is (y, x, length, palette_index) packed as 4 bytes and
hex-encoded (same approach as scripts/make_qr.py). The badge draws one
filled rectangle per run.

Outputs eat_well/sprites.py with ICONS and SPLASH_FRAMES.
"""

import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "assets_pixel")
OUT = os.path.join(ROOT, "eat_well", "sprites.py")

ICON_SIZE = 24       # icons drawn 1:1 on the diet filter screen
ICON_SM_SIZE = 12    # small icons for inline badges in list/detail rows
ICON_COLORS = 15     # +1 reserved for transparency
SPLASH_W, SPLASH_H = 80, 60   # drawn at 4x = 320x240 fullscreen
SPLASH_COLORS = 32


def is_magenta(r, g, b):
    return r > 200 and g < 80 and b > 200


def center_square(im):
    w, h = im.size
    s = min(w, h)
    return im.crop(((w - s) // 2, (h - s) // 2, (w - s) // 2 + s, (h - s) // 2 + s))


def quantize_icon(im, size):
    """Return (palette[(r,g,b)], pixel rows of palette-idx or -1 for transparent)."""
    im = center_square(im).resize((size, size), Image.NEAREST).convert("RGB")
    px = im.load()
    opaque = []
    mask = []
    for y in range(size):
        row = []
        for x in range(size):
            r, g, b = px[x, y]
            if is_magenta(r, g, b):
                row.append(-1)
            else:
                row.append((r, g, b))
                opaque.append((r, g, b))
        mask.append(row)
    # quantize opaque colors to ICON_COLORS
    tmp = Image.new("RGB", (len(opaque), 1))
    tmp.putdata(opaque)
    q = tmp.quantize(colors=ICON_COLORS, method=Image.MEDIANCUT).convert("RGB")
    pal = [q.getpixel((i, 0)) for i in range(ICON_COLORS)]
    # map each opaque pixel to nearest palette color
    qpx = q.load()
    idx = 0
    rows = []
    for y in range(size):
        out = []
        for x in range(size):
            v = mask[y][x]
            if v == -1:
                out.append(-1)
            else:
                out.append(nearest(v, pal))
                idx += 1
        rows.append(out)
    return pal, rows


def nearest(rgb, pal):
    r, g, b = rgb
    best, bestd = 0, 1 << 30
    for i, (pr, pg, pb) in enumerate(pal):
        d = (r - pr) ** 2 + (g - pg) ** 2 + (b - pb) ** 2
        if d < bestd:
            bestd, best = d, i
    return best


def quantize_splash(im):
    im = im.convert("RGB").resize((SPLASH_W, SPLASH_H), Image.LANCZOS)
    q = im.quantize(colors=SPLASH_COLORS, method=Image.MEDIANCUT, dither=Image.NONE)
    flat = q.getpalette() or []
    pal = [tuple(flat[i:i + 3]) for i in range(0, SPLASH_COLORS * 3, 3)]
    # getpalette may return fewer; pad
    while len(pal) < SPLASH_COLORS:
        pal.append((0, 0, 0))
    qp = q.load()
    rows = [[qp[x, y] for x in range(SPLASH_W)] for y in range(SPLASH_H)]
    return pal, rows


def rle(rows, w):
    """Rows of palette idx (-1 = transparent). Returns list of (y,x,ln,ci)."""
    runs = []
    for y, row in enumerate(rows):
        x = 0
        while x < w:
            ci = row[x]
            if ci < 0:
                x += 1
                continue
            x2 = x + 1
            while x2 < w and row[x2] == ci:
                x2 += 1
            ln = x2 - x
            while ln > 255:
                runs.append((y, x, 255, ci))
                x += 255
                ln -= 255
            runs.append((y, x, ln, ci))
            x = x2
    return runs


def pack(runs):
    return "".join("%02x%02x%02x%02x" % r for r in runs)


def main():
    icons = {}
    icons_sm = {}
    names = sorted(f[:-4] for f in os.listdir(ASSETS)
                   if f.endswith(".png") and not f.startswith("splash-"))
    total_runs = 0
    for name in names:
        src = Image.open(os.path.join(ASSETS, name + ".png"))
        pal, rows = quantize_icon(src, ICON_SIZE)
        runs = rle(rows, ICON_SIZE)
        total_runs += len(runs)
        icons[name] = (ICON_SIZE, ICON_SIZE, pal, pack(runs))
        pal_sm, rows_sm = quantize_icon(src, ICON_SM_SIZE)
        runs_sm = rle(rows_sm, ICON_SM_SIZE)
        total_runs += len(runs_sm)
        icons_sm[name] = (ICON_SM_SIZE, ICON_SM_SIZE, pal_sm, pack(runs_sm))
        print("%-22s %4d / %3d runs" % (name, len(runs), len(runs_sm)))

    frames = []
    for i in range(1, 5):
        pal, rows = quantize_splash(Image.open(os.path.join(ASSETS, "splash-%d.png" % i)))
        runs = rle(rows, SPLASH_W)
        frames.append((SPLASH_W, SPLASH_H, pal, pack(runs)))
        print("splash-%d %5d runs" % (i, len(runs)))

    with open(OUT, "w") as f:
        f.write('"""Pixel-art sprites generated by scripts/make_sprites.py. Do not edit."""\n\n')
        f.write("from badgeware import *\n\n\n")
        f.write("def _decode(hexdata):\n")
        f.write("    raw = bytearray(len(hexdata) // 2)\n")
        f.write("    for i in range(0, len(hexdata), 2):\n")
        f.write("        raw[i // 2] = int(hexdata[i:i + 2], 16)\n")
        f.write("    return raw\n\n\n")
        f.write("def _draw(w, h, pal, hexdata, x0, y0, scale):\n")
        f.write("    pens = [color.rgb(r, g, b) for (r, g, b) in pal]\n")
        f.write("    raw = _decode(hexdata)\n")
        f.write("    for i in range(0, len(raw), 4):\n")
        f.write("        y, x, ln, ci = raw[i], raw[i + 1], raw[i + 2], raw[i + 3]\n")
        f.write("        screen.pen = pens[ci]\n")
        f.write("        screen.rectangle(x0 + x * scale, y0 + y * scale,\n")
        f.write("                         ln * scale, scale)\n\n\n")
        f.write("def draw_icon(name, x, y, small=False):\n")
        f.write('    """Draw a pixel-art icon at (x, y): 24x24, or 12x12 if small."""\n')
        f.write("    w, h, pal, hexdata = (ICONS_SM if small else ICONS)[name]\n")
        f.write("    _draw(w, h, pal, hexdata, x, y, 1)\n\n\n")
        f.write("def draw_splash(frame):\n")
        f.write('    """Draw an 80x60 splash frame scaled 4x to fullscreen."""\n')
        f.write("    w, h, pal, hexdata = SPLASH_FRAMES[frame % len(SPLASH_FRAMES)]\n")
        f.write("    _draw(w, h, pal, hexdata, 0, 0, 4)\n\n\n")
        f.write("ICONS = {\n")
        for name in names:
            w, h, pal, hexdata = icons[name]
            f.write('    "%s": (%d, %d, %s,\n' % (name, w, h, pal))
            f.write('        "%s"),\n' % hexdata)
        f.write("}\n\n\nICONS_SM = {\n")
        for name in names:
            w, h, pal, hexdata = icons_sm[name]
            f.write('    "%s": (%d, %d, %s,\n' % (name, w, h, pal))
            f.write('        "%s"),\n' % hexdata)
        f.write("}\n\n\nSPLASH_FRAMES = [\n")
        for w, h, pal, hexdata in frames:
            f.write("    (%d, %d, %s,\n" % (w, h, pal))
            f.write('     "%s"),\n' % hexdata)
        f.write("]\n")
    size = os.path.getsize(OUT)
    print("wrote %s (%d bytes), icon runs total %d" % (OUT, size, total_runs))


if __name__ == "__main__":
    main()
